version: "3.8"
services:
    app:
        build: .
        container_name: detect_app
        ports:
            - 5000:5000
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/faces
    mongo:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data: